<Script>
 /*

 1. Write the program for creating the functional onload trigger mechanism in JavaScript

 2.write a JavaScript that is providing cross-browser supportthat should display "welcome to java script" whenever Dom content
   is loaded. the program should also display "Dom is loaded" when the
   Dom is loaded.

 3.a) write the steps to add the code generated by the modernizer into
   your script add the feature "HTML5 video".
   b) write a test program to check whether the feature is added or not.
 
 4.Write the program to loaded the Dom content and creating the functional onload trigger mechanism and integrating Modernizr inJavaScript
*/





</Script>